import { generateParcel } from '../generators/parcelGenerator';

export const commercialParcels = [
  generateParcel({
    id: 'COM001',
    title: 'Local Commercial Centre-Ville',
    titleDeedNumber: 'TC123456',
    address: '123 Rue du Commerce',
    city: 'Casablanca',
    surface: 250,
    type: 'COMMERCIAL',
    taxStatus: 'AVERAGE',
    status: 'AVAILABLE',
    zone: 'COMMERCIAL',
    ownerName: 'Mohammed Tazi',
    location: { lat: 33.5731, lng: -7.5898 },
    description: 'Local commercial idéalement situé en centre-ville',
    price: 2500000
  }),
  generateParcel({
    id: 'COM002',
    title: 'Bureau à Anfa',
    titleDeedNumber: 'TC123457',
    address: '456 Avenue des Nations',
    city: 'Casablanca',
    surface: 150,
    type: 'COMMERCIAL',
    taxStatus: 'PAID',
    status: 'AVAILABLE',
    zone: 'COMMERCIAL',
    ownerName: 'Fatima Zahra',
    location: { lat: 33.5735, lng: -7.5890 },
    description: 'Bureau moderne dans un quartier d'affaires',
    price: 1500000
  }),
  generateParcel({
    id: 'COM003',
    title: 'Magasin de Vêtements',
    titleDeedNumber: 'TC123458',
    address: '789 Rue de la Mode',
    city: 'Casablanca',
    surface: 200,
    type: 'COMMERCIAL',
    taxStatus: 'OVERDUE',
    status: 'UNAVAILABLE',
    zone: 'COMMERCIAL',
    ownerName: 'Sofia El Amrani',
    location: { lat: 33.5740, lng: -7.5900 },
    description: 'Magasin de vêtements avec une grande vitrine',
    price: 1800000
  }),
  generateParcel({
    id: 'COM004',
    title: 'Restaurant au Bord de Mer',
    titleDeedNumber: 'TC123459',
    address: '321 Boulevard de la Plage',
    city: 'Casablanca',
    surface: 300,
    type: 'COMMERCIAL',
    taxStatus: 'PAID',
    status: 'AVAILABLE',
    zone: 'COMMERCIAL',
    ownerName: 'Youssef Boulahdour',
    location: { lat: 33.5750, lng: -7.5910 },
    description: 'Restaurant avec vue sur la mer',
    price: 5000000
  }),
];