import { Parcel } from '../types';

export const commercialParcels: Parcel[] = [
  {
    id: "COM001",
    title: "Local Commercial Centre-ville",
    titleDeedNumber: "TF123456",
    address: "123 Rue du Commerce",
    city: "Casablanca",
    description: "Local commercial bien situé",
    surface: 150,
    type: "COMMERCIAL",
    zone: "COMMERCIAL_ZONE",
    taxStatus: "PAID",
    status: "IN_TRANSACTION",
    fiscal_status: "compliant",
    location: { lat: 33.5731, lng: -7.5898 },
    ownerName: "Mohammed Alami",
    price: 2500000,
    property_type: "COMMERCIAL",
    surface_area: 150,
    is_for_sale: true,
    owner_id: "owner1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tnbInfo: {
      pricePerMeter: 100,
      totalAmount: 15000,
      status: "PAID",
      lastUpdate: "2024-01-15"
    }
  },
  {
    id: "COM002",
    title: "Boutique Marina",
    titleDeedNumber: "TF789012",
    address: "45 Boulevard de la Marina",
    city: "Casablanca",
    description: "Boutique avec vue sur mer",
    surface: 80,
    type: "COMMERCIAL",
    zone: "URBAN",
    taxStatus: "PAID",
    status: "SOLD",
    fiscal_status: "compliant",
    location: { lat: 33.5931, lng: -7.6198 },
    ownerName: "Sara Bennani",
    price: 1800000,
    property_type: "COMMERCIAL",
    surface_area: 80,
    is_for_sale: false,
    owner_id: "owner2",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tnbInfo: {
      pricePerMeter: 120,
      totalAmount: 9600,
      status: "AVERAGE",
      lastUpdate: "2024-02-01"
    }
  },
  {
    id: "COM003",
    title: "Bureau Moderne",
    titleDeedNumber: "TF345678",
    address: "78 Avenue Hassan II",
    city: "Casablanca",
    description: "Espace de bureau moderne",
    surface: 200,
    type: "COMMERCIAL",
    zone: "URBAN",
    taxStatus: "PENDING",
    status: "AVAILABLE",
    fiscal_status: "under_review",
    location: { lat: 33.5831, lng: -7.6098 },
    ownerName: "Karim Idrissi",
    price: 3000000,
    property_type: "COMMERCIAL",
    surface_area: 200,
    is_for_sale: true,
    owner_id: "owner3",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tnbInfo: {
      pricePerMeter: 150,
      totalAmount: 30000,
      status: "AVERAGE",
      lastUpdate: "2024-01-20"
    }
  }
];