import { Parcel } from '../types';
import { createParcelWithTNB } from '../generators/parcelGenerator';

export const residentialParcels: Parcel[] = [
  createParcelWithTNB({
    id: '1',
    title: 'Villa Moderne - Californie',
    address: 'Rue des Jardins, Californie',
    city: 'casablanca',
    surface: 500,
    type: 'RESIDENTIAL',
    zone: 'URBAN',
    taxStatus: 'PAID',
    status: 'AVAILABLE',
    owner: 'Ahmed Benjelloun',
    location: { lat: 33.5731, lng: -7.6298 },
    titleDeedNumber: 'TF123456/C',
    ownerName: 'Ahmed Benjelloun'
  }),
  createParcelWithTNB({
    id: '2',
    title: 'Appartement Luxueux - Anfa',
    address: 'Avenue des F.A.R, Anfa',
    city: 'casablanca',
    surface: 120,
    type: 'RESIDENTIAL',
    zone: 'URBAN',
    taxStatus: 'PAID',
    status: 'AVAILABLE',
    owner: 'Fatima Zahra',
    location: { lat: 33.5881, lng: -7.6345 },
    titleDeedNumber: 'TF654321/C',
    ownerName: 'Fatima Zahra'
  }),
  createParcelWithTNB({
    id: '3',
    title: 'Maison de Ville - Maarif',
    address: 'Rue de la Liberté, Maarif',
    city: 'casablanca',
    surface: 300,
    type: 'RESIDENTIAL',
    zone: 'URBAN',
    taxStatus: 'PAID',
    status: 'AVAILABLE',
    owner: 'Mohamed El Amrani',
    location: { lat: 33.5912, lng: -7.6348 },
    titleDeedNumber: 'TF789012/C',
    ownerName: 'Mohamed El Amrani'
  }),
  createParcelWithTNB({
    id: '4',
    title: 'Terrain Résidentiel - Bouskoura',
    address: 'Route de Bouskoura',
    city: 'casablanca',
    surface: 1000,
    type: 'RESIDENTIAL',
    zone: 'URBAN',
    taxStatus: 'PAID',
    status: 'AVAILABLE',
    owner: 'Coopérative Al Firdaous',
    location: { lat: 33.5012, lng: -7.6584 },
    titleDeedNumber: 'TF901234/C',
    ownerName: 'Coopérative Al Firdaous'
  }),
  createParcelWithTNB({
    id: '5',
    title: 'Villa de Luxe - Ain Diab',
    address: 'Avenue de la Corniche, Ain Diab',
    city: 'casablanca',
    surface: 800,
    type: 'RESIDENTIAL',
    zone: 'URBAN',
    taxStatus: 'PAID',
    status: 'AVAILABLE',
    owner: 'Youssef El Khatib',
    location: { lat: 33.5889, lng: -7.6341 },
    titleDeedNumber: 'TF345678/C',
    ownerName: 'Youssef El Khatib'
  }),
];
