// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsnjvbvnyhcduczwaofx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzbmp2YnZueWhjZHVjendhb2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwMDIwMDEsImV4cCI6MjA1MDU3ODAwMX0.SRAEKVeY0LhFWWBbwsuZVCHpZuzmA5MIGM-oQ9Yn4AU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);