import { Parcel } from './types';

export const mockParcels: Parcel[] = [
  {
    id: '1',
    title: 'Villa de Luxe - Californie',
    address: '15 Boulevard de l\'Océan, Californie',
    city: 'casablanca',
    surface: 450,
    type: 'RESIDENTIAL',
    zone: 'E3',
    taxStatus: 'PAID',
    owner: 'Groupe Immobilier Atlas',
    location: { lat: 33.5731, lng: -7.5898 },
    titleDeedNumber: 'TF123456/C',
    ownerName: 'Ahmed El Fassi'
  },
  {
    id: '2',
    title: 'Terrain Commercial - Sidi Maârouf',
    address: '78 Zone Industrielle, Sidi Maârouf',
    city: 'casablanca',
    surface: 2500,
    type: 'COMMERCIAL',
    zone: 'I2S12',
    taxStatus: 'PENDING',
    owner: 'SARL Promocasa',
    location: { lat: 33.5933, lng: -7.6339 },
    titleDeedNumber: 'TF789012/C',
    ownerName: 'Société Promocasa'
  },
  {
    id: '3',
    title: 'Appartement Haut Standing - Gauthier',
    address: '45 Rue Jean Jaurès, Gauthier',
    city: 'casablanca',
    surface: 180,
    type: 'RESIDENTIAL',
    zone: 'E4',
    taxStatus: 'PAID',
    owner: 'Karim Benjelloun',
    location: { lat: 33.5850, lng: -7.6328 },
    titleDeedNumber: 'TF345678/C',
    ownerName: 'Karim Benjelloun'
  },
  {
    id: '4',
    title: 'Terrain Agricole - Bouskoura',
    address: 'Route de Bouskoura',
    city: 'casablanca',
    surface: 10000,
    type: 'AGRICULTURAL',
    zone: 'PROTECTED',
    taxStatus: 'PAID',
    owner: 'Coopérative Al Firdaous',
    location: { lat: 33.5012, lng: -7.6584 },
    titleDeedNumber: 'TF901234/C',
    ownerName: 'Coopérative Al Firdaous'
  },
  {
    id: '5',
    title: 'Local Commercial - Maarif',
    address: '156 Rue Zerktouni, Maarif',
    city: 'casablanca',
    surface: 120,
    type: 'COMMERCIAL',
    zone: 'BT2',
    taxStatus: 'OVERDUE',
    owner: 'Société Retail Plus',
    location: { lat: 33.5876, lng: -7.6331 },
    titleDeedNumber: 'TF567890/C',
    ownerName: 'Société Retail Plus'
  },
  {
    id: '6',
    title: 'Villa Modern - Anfa',
    address: '23 Boulevard d\'Anfa',
    city: 'casablanca',
    surface: 600,
    type: 'RESIDENTIAL',
    zone: 'E4',
    taxStatus: 'PAID',
    owner: 'Sofia Alaoui',
    location: { lat: 33.5932, lng: -7.6353 },
    titleDeedNumber: 'TF234567/C',
    ownerName: 'Sofia Alaoui'
  },
  {
    id: '7',
    title: 'Entrepôt Logistique - Ain Sebaa',
    address: '89 Zone Industrielle, Ain Sebaa',
    city: 'casablanca',
    surface: 5000,
    type: 'INDUSTRIAL',
    zone: 'I2S12',
    taxStatus: 'PAID',
    owner: 'Logistique Express SARL',
    location: { lat: 33.6167, lng: -7.5504 },
    titleDeedNumber: 'TF678901/C',
    ownerName: 'Logistique Express SARL'
  },
  {
    id: '8',
    title: 'Riad Traditionnel - Habous',
    address: '12 Quartier des Habous',
    city: 'casablanca',
    surface: 300,
    type: 'RESIDENTIAL',
    zone: 'PROTECTED',
    taxStatus: 'PENDING',
    owner: 'Hassan El Mansouri',
    location: { lat: 33.5892, lng: -7.6194 },
    titleDeedNumber: 'TF345678/C',
    ownerName: 'Hassan El Mansouri'
  },
  {
    id: '9',
    title: 'Centre Commercial - CIL',
    address: '234 Boulevard Mohammed V, CIL',
    city: 'casablanca',
    surface: 8000,
    type: 'COMMERCIAL',
    zone: 'BT2',
    taxStatus: 'PAID',
    owner: 'Groupe Commercial Maroc',
    location: { lat: 33.5731, lng: -7.6353 },
    titleDeedNumber: 'TF789012/C',
    ownerName: 'Groupe Commercial Maroc'
  },
  {
    id: '10',
    title: 'Terrain Constructible - Dar Bouazza',
    address: 'Route Côtière, Dar Bouazza',
    city: 'casablanca',
    surface: 1500,
    type: 'SEASIDE',
    zone: 'CONSTRUCTIBLE',
    taxStatus: 'PAID',
    owner: 'Immobilière Côtière SA',
    location: { lat: 33.5315, lng: -7.7481 },
    titleDeedNumber: 'TF123789/C',
    ownerName: 'Immobilière Côtière SA'
  },
  {
    id: '11',
    title: 'Complexe Résidentiel - Hay Hassani',
    address: '45 Rue Al Qods, Hay Hassani',
    city: 'casablanca',
    surface: 12000,
    type: 'RESIDENTIAL',
    zone: 'E3',
    taxStatus: 'PENDING',
    owner: 'Groupe Al Omrane',
    location: { lat: 33.5534, lng: -7.6584 },
    titleDeedNumber: 'TF456789/C',
    ownerName: 'Groupe Al Omrane'
  },
  {
    id: '12',
    title: 'Ferme Agricole - Bouskoura',
    address: 'Route de l\'Aéroport, Bouskoura',
    city: 'casablanca',
    surface: 25000,
    type: 'AGRICULTURAL',
    zone: 'PROTECTED',
    taxStatus: 'PAID',
    owner: 'Coopérative Al Baraka',
    location: { lat: 33.4989, lng: -7.6417 },
    titleDeedNumber: 'TF567123/C',
    ownerName: 'Coopérative Al Baraka'
  },
  {
    id: '13',
    title: 'Immeuble de Bureaux - Marina',
    address: '78 Boulevard des FAR, Marina',
    city: 'casablanca',
    surface: 3500,
    type: 'COMMERCIAL',
    zone: 'BT2',
    taxStatus: 'PAID',
    owner: 'Casa Business Center',
    location: { lat: 33.6069, lng: -7.6192 },
    titleDeedNumber: 'TF890123/C',
    ownerName: 'Casa Business Center'
  },
  {
    id: '14',
    title: 'Villa avec Piscine - Ain Diab',
    address: '34 Corniche, Ain Diab',
    city: 'casablanca',
    surface: 800,
    type: 'RESIDENTIAL',
    zone: 'E4',
    taxStatus: 'PAID',
    owner: 'Youssef El Alami',
    location: { lat: 33.5954, lng: -7.6697 },
    titleDeedNumber: 'TF234890/C',
    ownerName: 'Youssef El Alami'
  },
  {
    id: '15',
    title: 'Zone Industrielle - Sidi Bernoussi',
    address: '123 Zone Industrielle, Sidi Bernoussi',
    city: 'casablanca',
    surface: 15000,
    type: 'INDUSTRIAL',
    zone: 'I2S12',
    taxStatus: 'OVERDUE',
    owner: 'Industries Modernes SA',
    location: { lat: 33.6167, lng: -7.5167 },
    titleDeedNumber: 'TF678234/C',
    ownerName: 'Industries Modernes SA'
  },
  {
    id: '16',
    title: 'Appartement Vue Mer - Anfa Place',
    address: 'Boulevard de la Corniche, Anfa Place',
    city: 'casablanca',
    surface: 250,
    type: 'RESIDENTIAL',
    zone: 'E4',
    taxStatus: 'PAID',
    owner: 'Nadia Benjelloun',
    location: { lat: 33.5954, lng: -7.6697 },
    titleDeedNumber: 'TF901456/C',
    ownerName: 'Nadia Benjelloun'
  },
  {
    id: '17',
    title: 'Centre Médical - 2 Mars',
    address: '56 Boulevard 2 Mars',
    city: 'casablanca',
    surface: 1200,
    type: 'COMMERCIAL',
    zone: 'BT2',
    taxStatus: 'PAID',
    owner: 'Clinique Al Shifa',
    location: { lat: 33.5892, lng: -7.6194 },
    titleDeedNumber: 'TF345912/C',
    ownerName: 'Clinique Al Shifa'
  },
  {
    id: '18',
    title: 'Terrain Touristique - Tamaris',
    address: 'Route de Tamaris',
    city: 'casablanca',
    surface: 5000,
    type: 'SEASIDE',
    zone: 'CONSTRUCTIBLE',
    taxStatus: 'PENDING',
    owner: 'Groupe Touristique Atlas',
    location: { lat: 33.5315, lng: -7.7481 },
    titleDeedNumber: 'TF678345/C',
    ownerName: 'Groupe Touristique Atlas'
  },
  {
    id: '19',
    title: 'Résidence Sécurisée - Oasis',
    address: '90 Quartier Oasis',
    city: 'casablanca',
    surface: 4500,
    type: 'RESIDENTIAL',
    zone: 'E3',
    taxStatus: 'PAID',
    owner: 'Immobilière Prestige',
    location: { lat: 33.5534, lng: -7.6584 },
    titleDeedNumber: 'TF123567/C',
    ownerName: 'Immobilière Prestige'
  },
  {
    id: '20',
    title: 'Hangar Logistique - Lissasfa',
    address: '234 Zone Industrielle, Lissasfa',
    city: 'casablanca',
    surface: 3000,
    type: 'INDUSTRIAL',
    zone: 'I2S12',
    taxStatus: 'PAID',
    owner: 'Logistique Maroc SARL',
    location: { lat: 33.5315, lng: -7.6584 },
    titleDeedNumber: 'TF890567/C',
    ownerName: 'Logistique Maroc SARL'
  },
  {
    id: '21',
    title: 'Duplex de Luxe - Racine',
    address: '67 Rue Jean Jaurès, Racine',
    city: 'casablanca',
    surface: 220,
    type: 'RESIDENTIAL',
    zone: 'E4',
    taxStatus: 'PAID',
    owner: 'Sarah El Fassi',
    location: { lat: 33.5892, lng: -7.6353 },
    titleDeedNumber: 'TF234678/C',
    ownerName: 'Sarah El Fassi'
  },
  {
    id: '22',
    title: 'Showroom Automobile - Ain Sebaa',
    address: '345 Boulevard Moulay Slimane, Ain Sebaa',
    city: 'casablanca',
    surface: 1800,
    type: 'COMMERCIAL',
    zone: 'BT2',
    taxStatus: 'PENDING',
    owner: 'Auto Premium SARL',
    location: { lat: 33.6167, lng: -7.5504 },
    titleDeedNumber: 'TF567890/C',
    ownerName: 'Auto Premium SARL'
  },
  {
    id: '23',
    title: 'Terrain Constructible - Bouskoura Golf City',
    address: 'Bouskoura Golf City',
    city: 'casablanca',
    surface: 1000,
    type: 'RESIDENTIAL',
    zone: 'CONSTRUCTIBLE',
    taxStatus: 'PAID',
    owner: 'Golf Resort Development',
    location: { lat: 33.4989, lng: -7.6417 },
    titleDeedNumber: 'TF789123/C',
    ownerName: 'Golf Resort Development'
  },
  {
    id: '24',
    title: 'Usine de Production - Sidi Bernoussi',
    address: '567 Zone Industrielle, Sidi Bernoussi',
    city: 'casablanca',
    surface: 8000,
    type: 'INDUSTRIAL',
    zone: 'I2S12',
    taxStatus: 'OVERDUE',
    owner: 'Industries du Maroc SA',
    location: { lat: 33.6167, lng: -7.5167 },
    titleDeedNumber: 'TF901234/C',
    ownerName: 'Industries du Maroc SA'
  },
  {
    id: '25',
    title: 'Penthouse - Twin Center',
    address: 'Boulevard Zerktouni, Twin Center',
    city: 'casablanca',
    surface: 300,
    type: 'RESIDENTIAL',
    zone: 'E4',
    taxStatus: 'PAID',
    owner: 'Mohammed El Kettani',
    location: { lat: 33.5876, lng: -7.6331 },
    titleDeedNumber: 'TF345789/C',
    ownerName: 'Mohammed El Kettani'
  },
  {
    id: '26',
    title: 'Centre de Formation - Sidi Maarouf',
    address: '89 Quartier Industriel, Sidi Maarouf',
    city: 'casablanca',
    surface: 2500,
    type: 'COMMERCIAL',
    zone: 'BT2',
    taxStatus: 'PAID',
    owner: 'Institut de Formation Pro',
    location: { lat: 33.5534, lng: -7.6584 },
    titleDeedNumber: 'TF678912/C',
    ownerName: 'Institut de Formation Pro'
  },
  {
    id: '27',
    title: 'Villa Contemporaine - CIL',
    address: '23 Rue des Orangers, CIL',
    city: 'casablanca',
    surface: 400,
    type: 'RESIDENTIAL',
    zone: 'E3',
    taxStatus: 'PENDING',
    owner: 'Amina Benjelloun',
    location: { lat: 33.5731, lng: -7.6353 },
    titleDeedNumber: 'TF123890/C',
    ownerName: 'Amina Benjelloun'
  },
  {
    id: '28',
    title: 'Complexe Sportif - Californie',
    address: '456 Boulevard de l\'Atlas, Californie',
    city: 'casablanca',
    surface: 6000,
    type: 'MIXED',
    zone: 'E4',
    taxStatus: 'PAID',
    owner: 'Sport & Loisirs SA',
    location: { lat: 33.5731, lng: -7.5898 },
    titleDeedNumber: 'TF567123/C',
    ownerName: 'Sport & Loisirs SA'
  },
  {
    id: '29',
    title: 'Entrepôt Frigorifique - Lissasfa',
    address: '789 Zone Industrielle, Lissasfa',
    city: 'casablanca',
    surface: 4000,
    type: 'INDUSTRIAL',
    zone: 'I2S12',
    taxStatus: 'PAID',
    owner: 'Froid Logistique SARL',
    location: { lat: 33.5315, lng: -7.6584 },
    titleDeedNumber: 'TF890345/C',
    ownerName: 'Froid Logistique SARL'
  },
  {
    id: '30',
    title: 'Résidence Balnéaire - Dar Bouazza',
    address: 'Route Côtière, Dar Bouazza',
    city: 'casablanca',
    surface: 3500,
    type: 'SEASIDE',
    zone: 'CONSTRUCTIBLE',
    taxStatus: 'PENDING',
    owner: 'Groupe Immobilier Littoral',
    location: { lat: 33.5315, lng: -7.7481 },
    titleDeedNumber: 'TF234567/C',
    ownerName: 'Groupe Immobilier Littoral'
  }
];